// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package myerror

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD31a5a85Decode20212GORYACHIEMEKSIKANSIInternalsMyerror(in *jlexer.Lexer, out *ResultErrorMulti) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = int(in.Int())
		case "explain":
			out.Explain = string(in.String())
		case "body":
			if m, ok := out.Body.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Body.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Body = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD31a5a85Encode20212GORYACHIEMEKSIKANSIInternalsMyerror(out *jwriter.Writer, in ResultErrorMulti) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Status))
	}
	if in.Explain != "" {
		const prefix string = ",\"explain\":"
		out.RawString(prefix)
		out.String(string(in.Explain))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		if m, ok := in.Body.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Body.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Body))
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResultErrorMulti) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD31a5a85Encode20212GORYACHIEMEKSIKANSIInternalsMyerror(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResultErrorMulti) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD31a5a85Decode20212GORYACHIEMEKSIKANSIInternalsMyerror(l, v)
}
func easyjsonD31a5a85Decode20212GORYACHIEMEKSIKANSIInternalsMyerror1(in *jlexer.Lexer, out *ResultError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = int(in.Int())
		case "explain":
			out.Explain = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD31a5a85Encode20212GORYACHIEMEKSIKANSIInternalsMyerror1(out *jwriter.Writer, in ResultError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Status))
	}
	if in.Explain != "" {
		const prefix string = ",\"explain\":"
		out.RawString(prefix)
		out.String(string(in.Explain))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResultError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD31a5a85Encode20212GORYACHIEMEKSIKANSIInternalsMyerror1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResultError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD31a5a85Decode20212GORYACHIEMEKSIKANSIInternalsMyerror1(l, v)
}
