// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: promocode.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromoCodeWithAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromoCode  string `protobuf:"bytes,1,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	Amount     int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Restaurant int64  `protobuf:"varint,3,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
}

func (x *PromoCodeWithAmount) Reset() {
	*x = PromoCodeWithAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promocode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromoCodeWithAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoCodeWithAmount) ProtoMessage() {}

func (x *PromoCodeWithAmount) ProtoReflect() protoreflect.Message {
	mi := &file_promocode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoCodeWithAmount.ProtoReflect.Descriptor instead.
func (*PromoCodeWithAmount) Descriptor() ([]byte, []int) {
	return file_promocode_proto_rawDescGZIP(), []int{0}
}

func (x *PromoCodeWithAmount) GetPromoCode() string {
	if x != nil {
		return x.PromoCode
	}
	return ""
}

func (x *PromoCodeWithAmount) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PromoCodeWithAmount) GetRestaurant() int64 {
	if x != nil {
		return x.Restaurant
	}
	return 0
}

type PromoCodeWithRestaurantId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromoCode  string `protobuf:"bytes,1,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	Restaurant int64  `protobuf:"varint,2,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
}

func (x *PromoCodeWithRestaurantId) Reset() {
	*x = PromoCodeWithRestaurantId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promocode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromoCodeWithRestaurantId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoCodeWithRestaurantId) ProtoMessage() {}

func (x *PromoCodeWithRestaurantId) ProtoReflect() protoreflect.Message {
	mi := &file_promocode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoCodeWithRestaurantId.ProtoReflect.Descriptor instead.
func (*PromoCodeWithRestaurantId) Descriptor() ([]byte, []int) {
	return file_promocode_proto_rawDescGZIP(), []int{1}
}

func (x *PromoCodeWithRestaurantId) GetPromoCode() string {
	if x != nil {
		return x.PromoCode
	}
	return ""
}

func (x *PromoCodeWithRestaurantId) GetRestaurant() int64 {
	if x != nil {
		return x.Restaurant
	}
	return 0
}

type TypePromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  int64  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TypePromoCodeResponse) Reset() {
	*x = TypePromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promocode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypePromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypePromoCodeResponse) ProtoMessage() {}

func (x *TypePromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promocode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypePromoCodeResponse.ProtoReflect.Descriptor instead.
func (*TypePromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_promocode_proto_rawDescGZIP(), []int{2}
}

func (x *TypePromoCodeResponse) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TypePromoCodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NewCostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cost  int64  `protobuf:"varint,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *NewCostResponse) Reset() {
	*x = NewCostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promocode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCostResponse) ProtoMessage() {}

func (x *NewCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promocode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCostResponse.ProtoReflect.Descriptor instead.
func (*NewCostResponse) Descriptor() ([]byte, []int) {
	return file_promocode_proto_rawDescGZIP(), []int{3}
}

func (x *NewCostResponse) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *NewCostResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FreeDishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cost   int64  `protobuf:"varint,1,opt,name=cost,proto3" json:"cost,omitempty"`
	DishId int64  `protobuf:"varint,2,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FreeDishResponse) Reset() {
	*x = FreeDishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_promocode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreeDishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeDishResponse) ProtoMessage() {}

func (x *FreeDishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_promocode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeDishResponse.ProtoReflect.Descriptor instead.
func (*FreeDishResponse) Descriptor() ([]byte, []int) {
	return file_promocode_proto_rawDescGZIP(), []int{4}
}

func (x *FreeDishResponse) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *FreeDishResponse) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *FreeDishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_promocode_proto protoreflect.FileDescriptor

var file_promocode_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x6d,
	0x6f, 0x43, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43,
	0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x22, 0x41, 0x0a, 0x15, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3b, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x55, 0x0a, 0x10, 0x46, 0x72, 0x65, 0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x69,
	0x73, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x69, 0x73,
	0x68, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xa3, 0x03, 0x0a, 0x10, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x43, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x55, 0x0a, 0x19, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x73, 0x74,
	0x46, 0x6f, 0x72, 0x46, 0x72, 0x65, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x12,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49,
	0x64, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x15, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x46, 0x72, 0x65, 0x65, 0x44, 0x69,
	0x73, 0x68, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x43, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x72, 0x65,
	0x65, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x11, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x53, 0x61,
	0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x43, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74, 0x68, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x46, 0x6f, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x65, 0x77, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_promocode_proto_rawDescOnce sync.Once
	file_promocode_proto_rawDescData = file_promocode_proto_rawDesc
)

func file_promocode_proto_rawDescGZIP() []byte {
	file_promocode_proto_rawDescOnce.Do(func() {
		file_promocode_proto_rawDescData = protoimpl.X.CompressGZIP(file_promocode_proto_rawDescData)
	})
	return file_promocode_proto_rawDescData
}

var file_promocode_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_promocode_proto_goTypes = []interface{}{
	(*PromoCodeWithAmount)(nil),       // 0: proto.PromoCodeWithAmount
	(*PromoCodeWithRestaurantId)(nil), // 1: proto.PromoCodeWithRestaurantId
	(*TypePromoCodeResponse)(nil),     // 2: proto.TypePromoCodeResponse
	(*NewCostResponse)(nil),           // 3: proto.NewCostResponse
	(*FreeDishResponse)(nil),          // 4: proto.FreeDishResponse
}
var file_promocode_proto_depIdxs = []int32{
	1, // 0: proto.PromocodeService.GetTypePromoCode:input_type -> proto.PromoCodeWithRestaurantId
	1, // 1: proto.PromocodeService.ActiveCostForFreeDelivery:input_type -> proto.PromoCodeWithRestaurantId
	1, // 2: proto.PromocodeService.ActiveCostForFreeDish:input_type -> proto.PromoCodeWithRestaurantId
	0, // 3: proto.PromocodeService.ActiveCostForSale:input_type -> proto.PromoCodeWithAmount
	0, // 4: proto.PromocodeService.ActiveTimeForSale:input_type -> proto.PromoCodeWithAmount
	2, // 5: proto.PromocodeService.GetTypePromoCode:output_type -> proto.TypePromoCodeResponse
	3, // 6: proto.PromocodeService.ActiveCostForFreeDelivery:output_type -> proto.NewCostResponse
	4, // 7: proto.PromocodeService.ActiveCostForFreeDish:output_type -> proto.FreeDishResponse
	3, // 8: proto.PromocodeService.ActiveCostForSale:output_type -> proto.NewCostResponse
	3, // 9: proto.PromocodeService.ActiveTimeForSale:output_type -> proto.NewCostResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_promocode_proto_init() }
func file_promocode_proto_init() {
	if File_promocode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_promocode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromoCodeWithAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promocode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromoCodeWithRestaurantId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promocode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypePromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promocode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_promocode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreeDishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_promocode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_promocode_proto_goTypes,
		DependencyIndexes: file_promocode_proto_depIdxs,
		MessageInfos:      file_promocode_proto_msgTypes,
	}.Build()
	File_promocode_proto = out.File
	file_promocode_proto_rawDesc = nil
	file_promocode_proto_goTypes = nil
	file_promocode_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PromocodeServiceClient is the client API for PromocodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PromocodeServiceClient interface {
	GetTypePromoCode(ctx context.Context, in *PromoCodeWithRestaurantId, opts ...grpc.CallOption) (*TypePromoCodeResponse, error)
	ActiveCostForFreeDelivery(ctx context.Context, in *PromoCodeWithRestaurantId, opts ...grpc.CallOption) (*NewCostResponse, error)
	ActiveCostForFreeDish(ctx context.Context, in *PromoCodeWithRestaurantId, opts ...grpc.CallOption) (*FreeDishResponse, error)
	ActiveCostForSale(ctx context.Context, in *PromoCodeWithAmount, opts ...grpc.CallOption) (*NewCostResponse, error)
	ActiveTimeForSale(ctx context.Context, in *PromoCodeWithAmount, opts ...grpc.CallOption) (*NewCostResponse, error)
}

type promocodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromocodeServiceClient(cc grpc.ClientConnInterface) PromocodeServiceClient {
	return &promocodeServiceClient{cc}
}

func (c *promocodeServiceClient) GetTypePromoCode(ctx context.Context, in *PromoCodeWithRestaurantId, opts ...grpc.CallOption) (*TypePromoCodeResponse, error) {
	out := new(TypePromoCodeResponse)
	err := c.cc.Invoke(ctx, "/proto.PromocodeService/GetTypePromoCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promocodeServiceClient) ActiveCostForFreeDelivery(ctx context.Context, in *PromoCodeWithRestaurantId, opts ...grpc.CallOption) (*NewCostResponse, error) {
	out := new(NewCostResponse)
	err := c.cc.Invoke(ctx, "/proto.PromocodeService/ActiveCostForFreeDelivery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promocodeServiceClient) ActiveCostForFreeDish(ctx context.Context, in *PromoCodeWithRestaurantId, opts ...grpc.CallOption) (*FreeDishResponse, error) {
	out := new(FreeDishResponse)
	err := c.cc.Invoke(ctx, "/proto.PromocodeService/ActiveCostForFreeDish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promocodeServiceClient) ActiveCostForSale(ctx context.Context, in *PromoCodeWithAmount, opts ...grpc.CallOption) (*NewCostResponse, error) {
	out := new(NewCostResponse)
	err := c.cc.Invoke(ctx, "/proto.PromocodeService/ActiveCostForSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promocodeServiceClient) ActiveTimeForSale(ctx context.Context, in *PromoCodeWithAmount, opts ...grpc.CallOption) (*NewCostResponse, error) {
	out := new(NewCostResponse)
	err := c.cc.Invoke(ctx, "/proto.PromocodeService/ActiveTimeForSale", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromocodeServiceServer is the server API for PromocodeService service.
type PromocodeServiceServer interface {
	GetTypePromoCode(context.Context, *PromoCodeWithRestaurantId) (*TypePromoCodeResponse, error)
	ActiveCostForFreeDelivery(context.Context, *PromoCodeWithRestaurantId) (*NewCostResponse, error)
	ActiveCostForFreeDish(context.Context, *PromoCodeWithRestaurantId) (*FreeDishResponse, error)
	ActiveCostForSale(context.Context, *PromoCodeWithAmount) (*NewCostResponse, error)
	ActiveTimeForSale(context.Context, *PromoCodeWithAmount) (*NewCostResponse, error)
}

// UnimplementedPromocodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPromocodeServiceServer struct {
}

func (*UnimplementedPromocodeServiceServer) GetTypePromoCode(context.Context, *PromoCodeWithRestaurantId) (*TypePromoCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTypePromoCode not implemented")
}
func (*UnimplementedPromocodeServiceServer) ActiveCostForFreeDelivery(context.Context, *PromoCodeWithRestaurantId) (*NewCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveCostForFreeDelivery not implemented")
}
func (*UnimplementedPromocodeServiceServer) ActiveCostForFreeDish(context.Context, *PromoCodeWithRestaurantId) (*FreeDishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveCostForFreeDish not implemented")
}
func (*UnimplementedPromocodeServiceServer) ActiveCostForSale(context.Context, *PromoCodeWithAmount) (*NewCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveCostForSale not implemented")
}
func (*UnimplementedPromocodeServiceServer) ActiveTimeForSale(context.Context, *PromoCodeWithAmount) (*NewCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveTimeForSale not implemented")
}

func RegisterPromocodeServiceServer(s *grpc.Server, srv PromocodeServiceServer) {
	s.RegisterService(&_PromocodeService_serviceDesc, srv)
}

func _PromocodeService_GetTypePromoCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoCodeWithRestaurantId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromocodeServiceServer).GetTypePromoCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PromocodeService/GetTypePromoCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromocodeServiceServer).GetTypePromoCode(ctx, req.(*PromoCodeWithRestaurantId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromocodeService_ActiveCostForFreeDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoCodeWithRestaurantId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromocodeServiceServer).ActiveCostForFreeDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PromocodeService/ActiveCostForFreeDelivery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromocodeServiceServer).ActiveCostForFreeDelivery(ctx, req.(*PromoCodeWithRestaurantId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromocodeService_ActiveCostForFreeDish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoCodeWithRestaurantId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromocodeServiceServer).ActiveCostForFreeDish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PromocodeService/ActiveCostForFreeDish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromocodeServiceServer).ActiveCostForFreeDish(ctx, req.(*PromoCodeWithRestaurantId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromocodeService_ActiveCostForSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoCodeWithAmount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromocodeServiceServer).ActiveCostForSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PromocodeService/ActiveCostForSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromocodeServiceServer).ActiveCostForSale(ctx, req.(*PromoCodeWithAmount))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromocodeService_ActiveTimeForSale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoCodeWithAmount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromocodeServiceServer).ActiveTimeForSale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PromocodeService/ActiveTimeForSale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromocodeServiceServer).ActiveTimeForSale(ctx, req.(*PromoCodeWithAmount))
	}
	return interceptor(ctx, in, info, handler)
}

var _PromocodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PromocodeService",
	HandlerType: (*PromocodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTypePromoCode",
			Handler:    _PromocodeService_GetTypePromoCode_Handler,
		},
		{
			MethodName: "ActiveCostForFreeDelivery",
			Handler:    _PromocodeService_ActiveCostForFreeDelivery_Handler,
		},
		{
			MethodName: "ActiveCostForFreeDish",
			Handler:    _PromocodeService_ActiveCostForFreeDish_Handler,
		},
		{
			MethodName: "ActiveCostForSale",
			Handler:    _PromocodeService_ActiveCostForSale_Handler,
		},
		{
			MethodName: "ActiveTimeForSale",
			Handler:    _PromocodeService_ActiveTimeForSale_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promocode.proto",
}
