package Errors

type ResultError struct {
	Status	int         `json:"status"`
	Explain	string		`json:"parsedJSON,omitempty"`
}

const(
	ERRDB = "ERROR: database is not responding"
	ERRENCODE = "ERROR: Encode"
	ERRUNMARSHAL = "ERROR: unmarshal json"
	ERRAUTH = "ERROR: authorization failed"
	ERRPHONEQUERY = "ERROR: phone error query"
	ERRPHONESCAN  = "ERROR: phone not scan"
	ERRPHONEPASSQUERY = "ERROR: password and phone error query"
	ERRPHONEPASSSCAN  = "ERROR: phone and password not scan"
	ERRMAILQUERY = "ERROR: email error query"
	ERRMAILSCAN = "ERROR: email not scan"
	ERRMAILPASSQUERY = "ERROR: password or email error query"
	ERRMAILPASSSCAN  = "ERROR: email and pass not scan"
	ERRNOTLOGINORPASSWORD = "Неправильный логин или пароль"
	ERRINFOQUERY = "ERROR: not insert info query"
	ERRINFOSCAN = "ERROR: info not scan"
	ERRINSERTHOSTQUERY = "ERROR: not insert host query"
	ERRINSERTCOURIERQUERY = "ERROR: not insert courier query"
	ERRINSERTCLIENTQUERY = "ERROR: not insert client query"
	ERRINSERTCOOKIEQUERY = "ERROR: not insert cookie transact query"
	ERRDELETECOOKIEQUERY = "ERROR: cookie not delete query"
	ERRINSERTLOGINCOOKIEQUERY = "ERROR: not insert cookie query"
	ERRUNIQUE = "Телефон или email уже зарегистрирован"
	ERRCREATEQUERY = "ERROR: db not created"
	ERRINSERTQUERY = "ERROR: restaurant not insert"
	ERRCOOKIEANDCSRFQUERY = "ERROR: cookie and csrf query"
	ERRCOOKIEANDCSRFSCAN = "ERROR: cookie and csrf scan"
	ERRCOOKIEQUERY = "ERROR: cookie query"
	ERRCOOKIESCAN = "ERROR: cookie scan"
	ERRSIDNOTFOUND = "ERROR: id not found"
	ERRNOTCONNECT      = "ERROR: not connect"
	ERRUPDATECSRFQUERY = "ERROR: csrf not updated"
	ERRCOOKIEEXPIRED   = "ERROR: cookie expired"
	ERRDELETEQUERY = "ERROR: not delete query"
	ERRINSERTROOTQUERY = "ERROR: not create root"
	ERRCLIENTQUERY = "ERROR: check user on client query"
	ERRCLIENTSCAN = "ERROR: check user on client not scan"
	ERRHOSTQUERY = "ERROR: check user on host query"
	ERRHOSTSCAN = "ERROR: check user on host not scan"
	ERRCORIERQUERY = "ERROR: check user on courier query"
	ERRCORIERSCAN = "ERROR: check user on courier not scan"
	ERRGETPROFILEHOSTQUERY = "ERROR: profile host query"
	ERRGETPROFILEHOSTSCAN = "ERROR: profile host not scan"
	ERRGETPROFILECLIENTQUERY = "ERROR: profile client query"
	ERRGETPROFILECLIENTSCAN = "ERROR: profile client not scan"
	ERRGETBIRTHDAYQUERY = "ERROR: birthday query"
	ERRGETBIRTHDAYSCAN = "ERROR: birthday not scan"
	ERRGETPROFILECOURIERQUERY = "ERROR: profile courier query"
	ERRGETPROFILECOURIERSCAN = "ERROR: profile courier not scan"
	ERRQUERY = "ERROR: restaurant not get"
	ERRSCAN = "ERROR: restaurant scan error"
	RESTNULL = "ERROR: restaurants not found"
	ERRCOOKIEIDNOTFOUND = "ERROR: id by cookie not found"
	ERRINSERTROOTCLIENTQUERY = "ERROR: root not insert in client"
)
