// Code generated by MockGen. DO NOT EDIT.
// Source: 2021_2_GORYACHIE_MEKSIKANSI/internals/cart/orm (interfaces: WrapperCartServerInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	cart "2021_2_GORYACHIE_MEKSIKANSI/internals/cart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWrapperCartServerInterface is a mock of WrapperCartServerInterface interface.
type MockWrapperCartServerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWrapperCartServerInterfaceMockRecorder
}

// MockWrapperCartServerInterfaceMockRecorder is the mock recorder for MockWrapperCartServerInterface.
type MockWrapperCartServerInterfaceMockRecorder struct {
	mock *MockWrapperCartServerInterface
}

// NewMockWrapperCartServerInterface creates a new mock instance.
func NewMockWrapperCartServerInterface(ctrl *gomock.Controller) *MockWrapperCartServerInterface {
	mock := &MockWrapperCartServerInterface{ctrl: ctrl}
	mock.recorder = &MockWrapperCartServerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWrapperCartServerInterface) EXPECT() *MockWrapperCartServerInterfaceMockRecorder {
	return m.recorder
}

// AddPromoCode mocks base method.
func (m *MockWrapperCartServerInterface) AddPromoCode(arg0 string, arg1, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPromoCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPromoCode indicates an expected call of AddPromoCode.
func (mr *MockWrapperCartServerInterfaceMockRecorder) AddPromoCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPromoCode", reflect.TypeOf((*MockWrapperCartServerInterface)(nil).AddPromoCode), arg0, arg1, arg2)
}

// GetCart mocks base method.
func (m *MockWrapperCartServerInterface) GetCart(arg0 int) (*cart.ResponseCartErrors, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", arg0)
	ret0, _ := ret[0].(*cart.ResponseCartErrors)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockWrapperCartServerInterfaceMockRecorder) GetCart(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockWrapperCartServerInterface)(nil).GetCart), arg0)
}

// UpdateCart mocks base method.
func (m *MockWrapperCartServerInterface) UpdateCart(arg0 cart.RequestCartDefault, arg1 int) (*cart.ResponseCartErrors, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCart", arg0, arg1)
	ret0, _ := ret[0].(*cart.ResponseCartErrors)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCart indicates an expected call of UpdateCart.
func (mr *MockWrapperCartServerInterfaceMockRecorder) UpdateCart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCart", reflect.TypeOf((*MockWrapperCartServerInterface)(nil).UpdateCart), arg0, arg1)
}
