global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['monolith:5000']
  - job_name: 'system'
    static_configs:
      - targets: ['nodeExporter:9101']
